#! /usr/bin/env ruby
require 'optparse' 
require File.join(File.join(File.dirname(__FILE__), "muzukashi"))

help = <<HELP
Muzukashi is a small issue tracker.
HELP

case ARGV[0]
when "init"
  if Muzukashi.create_cage(".")
    puts "cage created. now go hunt some bugs."
  end
when "add"
  if ARGV[1].nil?
    puts "need a bug."
    exit
   end
  if Muzukashi.capture_bug(ARGV[1])
    puts "succes."
  end

when nil
Muzukashi.read_bugs(true)
when "help"
  puts help

when "rm"
  if ARGV[1].nil?
    puts "you need to tell me an id to delete"
    exit
  end
  Muzukashi.remove_bug(ARGV[0])
end


